---
title: "In class exercise 6"
date: '13 February 2023'
date-modified: '`r Sys.Date()`'
execute: 
  eval: true
  echo: true
  warning: false
editor: visual
---

#1 Load Data
```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse)
```

Let's start by importing Geospatial data
```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

Next, Aspatial data
```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan_GDPPC <- left_join(hunan, hunan2012) %>%
  select(1:4, 7,  15)
```

#2 Visualising plot

```{r}
tmap_mode("plot")

tm_shape(hunan_GDPPC) +
  tm_fill("GDPPC",
          style = "quantile",
          palette = "Blues",
          title = "GDPPC") +
  tm_layout(main.title =  "Distribution of GDP per capita by distribution",
  main.title.position = "center",
  main.title.size = 0.9,
  legend.height = 0.45,
  legend.width = 0.35,
  frame = TRUE) +
  tm_borders(alpha = 0.5) +
  tm_compass(type = "8star", size = 2) +
  tm_scale_bar() +
  tm_grid(alpha = 0.2)
  
```

#3 Computing using different Contiguity neighbour methods

queen method
```{r}
cn_queen <- hunan_GDPPC %>%
  mutate(nb = st_contiguity(geometry),
         .before = 1)
```

rook method
```{r}
cn_rook <- hunan_GDPPC %>%
  mutate(nb = st_contiguity(geometry),
         queen = FALSE,
         .before = 1)
```

#4 Contiguity weights
queen method
```{r}
wm_q <- hunan_GDPPC %>%
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(nb),
         .before = 1)
```

